# Generated by Django 5.2.4 on 2025-07-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='number')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'generation',
                'verbose_name_plural': 'generations',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('version', models.CharField(max_length=64, verbose_name='version')),
                ('hp', models.PositiveSmallIntegerField(verbose_name='hp')),
                ('attack', models.PositiveSmallIntegerField(verbose_name='attack')),
                ('defense', models.PositiveSmallIntegerField(verbose_name='defense')),
                ('special_attack', models.PositiveSmallIntegerField(verbose_name='special attack')),
                ('special_defense', models.PositiveSmallIntegerField(verbose_name='special defense')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='speed')),
                ('legendary', models.BooleanField(default=False, verbose_name='legendary')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokemon.generation', verbose_name='generation')),
                ('type1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_type1', to='pokemon.type', verbose_name='type 1')),
                ('type2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_type2', to='pokemon.type', verbose_name='type 2')),
            ],
            options={
                'verbose_name': 'pokémon',
                'verbose_name_plural': 'pokémons',
                'unique_together': {('number', 'name', 'version')},
            },
        ),
    ]
