# Generated by Django 5.2.4 on 2025-07-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name': 'type', 'verbose_name_plural': 'types'},
        ),
    ]
