# Generated by Django 5.2.4 on 2025-07-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_type_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generation',
            options={'ordering': ['number'], 'verbose_name': 'generation', 'verbose_name_plural': 'generations'},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_type2', to='pokemon.type', verbose_name='type 2'),
        ),
    ]
