# Generated by Django 5.2.4 on 2025-07-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_generation_options_alter_pokemon_type2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'permissions': [('change_legendary_pokemon', 'Can change legendary Pokémons')], 'verbose_name': 'pokémon', 'verbose_name_plural': 'pokémons'},
        ),
    ]
